#!/usr/bin/env node
// Generates docs/CHEATSHEET.md + docs/SKILLS.md from the stage manifests and
// each skill's SKILL.md frontmatter. THE FRESHNESS FIX (IDEA-018): the per-mode
// skill/agent/loop lists become a build artifact, not a memory test — so these
// docs can't rot the way the README did (19 releases stale before v0.42.1).
//
//   npm run gen:docs
//
// Reads the same src/modes.js source `boss map` reads, so the static cheatsheet
// and the live map can never disagree.

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { BOSS_ROOT, bossVersion } from '../src/paths.js';
import { loadModes, packageSkillMd, skillGloss, modeWord } from '../src/modes.js';
import { reportWayfindingDrift } from './check-wayfinding-drift.js';

const V = bossVersion();
const banner = (cmd) =>
  `<!-- GENERATED by scripts/gen-docs.js — do not edit by hand. Run \`${cmd}\` to refresh. -->`;

const modes = loadModes();

// Standing commands — true in every mode (the git-cheatsheet core).
const STANDING = [
  ['boss new <name>', 'scaffold a new project (Quickstart mode)'],
  ['boss map', 'live cheatsheet: where you are + what’s one unlock away'],
  ['boss board', 'what’s in flight (captured → shipped)'],
  ['boss status [--conscience]', 'mode / pinned version / drift (+ loop states)'],
  ['boss unlock <mode>', 'climb a rung: quickstart → mvp → v1 → scale'],
  ['boss conscience pause --for 8h', 'silence the whole conscience for a bounded sprint'],
  ['boss conscience resume', 're-enable the conscience'],
  ['boss conscience mute <moment>', 'turn down ONE moment (drift|caution|…); unmute to bring it back'],
  ['/boss-sync', 'pull the latest BOSS practices into this project (DOWN)'],
  ['/boss-learn', 'route a proven pattern UP into the library or DOWN into the app'],
];

// Package SKILL.md files carry scaffold-time placeholders ({{PROJECT_NAME}}) that
// only get substituted at `boss new`. In the generic cheatsheet they read wrong,
// so neutralize them. (`boss map` never hits this — it reads the project's own
// already-substituted copies.)
const clean = (s) => (s || '').replace(/\{\{PROJECT_NAME\}\}/g, 'your app').replace(/\{\{[^}]+\}\}/g, '');

function skillRows(mode) {
  return (mode.skills || []).map((s) => {
    const { gloss, usage } = skillGloss(packageSkillMd(mode.id, s));
    return { name: s, gloss: clean(gloss), usage: clean(usage) };
  });
}

// ---- docs/CHEATSHEET.md ---------------------------------------------------
function cheatsheet() {
  const out = [];
  out.push(banner('npm run gen:docs'));
  out.push('');
  out.push('# BOSS Cheatsheet');
  out.push('');
  out.push(`> The whole ladder at a glance — every mode and what it adds. Generated from the stage`);
  out.push(`> manifests, current as of **v${V}**. Inside a project, run \`boss map\` for the live,`);
  out.push('> personalized version (where you are + what’s one unlock away).');
  out.push('');
  out.push('## The ladder');
  out.push('');
  out.push('`Quickstart → MVP → V1 → Scale`. Each unlock is **additive and your call** — nothing is');
  out.push('removed, and a project that stays in Quickstart forever is a legitimate project.');
  out.push('');
  out.push('## Standing commands (any mode)');
  out.push('');
  out.push('| Command | What |');
  out.push('|---|---|');
  for (const [cmd, what] of STANDING) out.push(`| \`${cmd}\` | ${what} |`);
  out.push('');

  for (const mode of modes) {
    const next = mode.unlocksNext ? `  ·  unlock next: \`boss unlock ${modeWord(mode.unlocksNext)}\`` : '';
    out.push(`## ${mode.name}${next}`);
    out.push('');
    if (!mode.authored) {
      out.push('_Not authored yet (stubbed)._');
      out.push('');
      continue;
    }
    const rows = skillRows(mode);
    if (rows.length) {
      out.push('**Skills**');
      out.push('');
      for (const r of rows) out.push(`- \`/${r.name}\` — ${r.gloss || '—'}`);
      out.push('');
    }
    if ((mode.agents || []).length) out.push(`**Agents:** ${mode.agents.join(', ')}  `);
    if ((mode.loops || []).length) out.push(`**Loops:** ${mode.loops.join(', ')}  `);
    if ((mode.hooks || []).length) out.push(`**Hooks:** ${mode.hooks.join(', ')}  `);
    out.push('');
    if (mode.graduationHint) {
      out.push(`> _When to unlock next:_ ${mode.graduationHint}`);
      out.push('');
    }
  }

  out.push('---');
  out.push('');
  out.push('_Regenerate with `npm run gen:docs` after any mode/skill change. See [GUIDE.md](GUIDE.md)');
  out.push('for the walkthrough and [SKILLS.md](SKILLS.md) for the full skill reference._');
  out.push('');
  return out.join('\n');
}

// ---- docs/SKILLS.md -------------------------------------------------------
function skillsReference() {
  const out = [];
  out.push(banner('npm run gen:docs'));
  out.push('');
  out.push('# BOSS Skill Reference');
  out.push('');
  out.push(`> One line per skill, grouped by the mode that introduces it. Generated from each`);
  out.push(`> skill's \`SKILL.md\` frontmatter, current as of **v${V}**.`);
  out.push('');
  for (const mode of modes) {
    if (!mode.authored) continue;
    const rows = skillRows(mode);
    if (!rows.length) continue;
    out.push(`## ${mode.name}`);
    out.push('');
    for (const r of rows) {
      const usage = r.usage ? `  _(${r.usage})_` : '';
      out.push(`- **\`/${r.name}\`** — ${r.gloss || '—'}${usage}`);
    }
    out.push('');
  }
  out.push('---');
  out.push('');
  out.push('_Regenerate with `npm run gen:docs`._');
  out.push('');
  return out.join('\n');
}

const docsDir = join(BOSS_ROOT, 'docs');
writeFileSync(join(docsDir, 'CHEATSHEET.md'), cheatsheet());
writeFileSync(join(docsDir, 'SKILLS.md'), skillsReference());
console.log(`  ✦ Generated docs/CHEATSHEET.md + docs/SKILLS.md (v${V})`);

// Courtesy nudge: the generated docs just refreshed automatically — did the
// hand-authored GUIDE.md keep up? (IDEA-035; never blocks.)
reportWayfindingDrift();
